CXX = g++
CXXFLAGS = -std=c++17 -Wall
OBJS = P97156-numbers-in-an-interval.cc

all: programa

programa: $(OBJS)
	$(CXX) $(CXXFLGAS) -o $@ $(OBJS)

clean:
	rm programa
	echo "El programa ha sido eliminado"
